version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: ${MONGODB_DATABASE_CONTAINER_NAME}
    ports:
      - "27030:27017"
    volumes:
      - todo_mongodb_data:/data/db
    env_file:
      - .env
  mongodb_test:
    image: mongo:latest
    container_name: ${MONGODB_TEST_DATABASE_CONTAINER_NAME}
    ports:
      - "27031:27017"
    volumes:
      - todo_test_data:/data/db
    env_file:
      - .env
volumes:
  todo_mongodb_data:
  todo_test_data: