// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.2
// source: todolist.proto

package todolist

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ToDo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Status      bool   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Id          string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ToDo) Reset() {
	*x = ToDo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todolist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToDo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToDo) ProtoMessage() {}

func (x *ToDo) ProtoReflect() protoreflect.Message {
	mi := &file_todolist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToDo.ProtoReflect.Descriptor instead.
func (*ToDo) Descriptor() ([]byte, []int) {
	return file_todolist_proto_rawDescGZIP(), []int{0}
}

func (x *ToDo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToDo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToDo) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *ToDo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateToDoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Todo *ToDo `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
}

func (x *CreateToDoReq) Reset() {
	*x = CreateToDoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todolist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateToDoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateToDoReq) ProtoMessage() {}

func (x *CreateToDoReq) ProtoReflect() protoreflect.Message {
	mi := &file_todolist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateToDoReq.ProtoReflect.Descriptor instead.
func (*CreateToDoReq) Descriptor() ([]byte, []int) {
	return file_todolist_proto_rawDescGZIP(), []int{1}
}

func (x *CreateToDoReq) GetTodo() *ToDo {
	if x != nil {
		return x.Todo
	}
	return nil
}

type CreateToDoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Todo *ToDo `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
}

func (x *CreateToDoRes) Reset() {
	*x = CreateToDoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todolist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateToDoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateToDoRes) ProtoMessage() {}

func (x *CreateToDoRes) ProtoReflect() protoreflect.Message {
	mi := &file_todolist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateToDoRes.ProtoReflect.Descriptor instead.
func (*CreateToDoRes) Descriptor() ([]byte, []int) {
	return file_todolist_proto_rawDescGZIP(), []int{2}
}

func (x *CreateToDoRes) GetTodo() *ToDo {
	if x != nil {
		return x.Todo
	}
	return nil
}

type UpdateToDoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Todo *ToDo `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
}

func (x *UpdateToDoReq) Reset() {
	*x = UpdateToDoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todolist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateToDoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateToDoReq) ProtoMessage() {}

func (x *UpdateToDoReq) ProtoReflect() protoreflect.Message {
	mi := &file_todolist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateToDoReq.ProtoReflect.Descriptor instead.
func (*UpdateToDoReq) Descriptor() ([]byte, []int) {
	return file_todolist_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateToDoReq) GetTodo() *ToDo {
	if x != nil {
		return x.Todo
	}
	return nil
}

type UpdateToDoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Todo *ToDo `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
}

func (x *UpdateToDoRes) Reset() {
	*x = UpdateToDoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todolist_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateToDoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateToDoRes) ProtoMessage() {}

func (x *UpdateToDoRes) ProtoReflect() protoreflect.Message {
	mi := &file_todolist_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateToDoRes.ProtoReflect.Descriptor instead.
func (*UpdateToDoRes) Descriptor() ([]byte, []int) {
	return file_todolist_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateToDoRes) GetTodo() *ToDo {
	if x != nil {
		return x.Todo
	}
	return nil
}

type ReadToDoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReadToDoReq) Reset() {
	*x = ReadToDoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todolist_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadToDoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadToDoReq) ProtoMessage() {}

func (x *ReadToDoReq) ProtoReflect() protoreflect.Message {
	mi := &file_todolist_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadToDoReq.ProtoReflect.Descriptor instead.
func (*ReadToDoReq) Descriptor() ([]byte, []int) {
	return file_todolist_proto_rawDescGZIP(), []int{5}
}

func (x *ReadToDoReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadToDoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Todo *ToDo `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
}

func (x *ReadToDoRes) Reset() {
	*x = ReadToDoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todolist_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadToDoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadToDoRes) ProtoMessage() {}

func (x *ReadToDoRes) ProtoReflect() protoreflect.Message {
	mi := &file_todolist_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadToDoRes.ProtoReflect.Descriptor instead.
func (*ReadToDoRes) Descriptor() ([]byte, []int) {
	return file_todolist_proto_rawDescGZIP(), []int{6}
}

func (x *ReadToDoRes) GetTodo() *ToDo {
	if x != nil {
		return x.Todo
	}
	return nil
}

type DeleteToDoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteToDoReq) Reset() {
	*x = DeleteToDoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todolist_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteToDoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteToDoReq) ProtoMessage() {}

func (x *DeleteToDoReq) ProtoReflect() protoreflect.Message {
	mi := &file_todolist_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteToDoReq.ProtoReflect.Descriptor instead.
func (*DeleteToDoReq) Descriptor() ([]byte, []int) {
	return file_todolist_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteToDoReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteToDoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DeleteToDoRes) Reset() {
	*x = DeleteToDoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todolist_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteToDoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteToDoRes) ProtoMessage() {}

func (x *DeleteToDoRes) ProtoReflect() protoreflect.Message {
	mi := &file_todolist_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteToDoRes.ProtoReflect.Descriptor instead.
func (*DeleteToDoRes) Descriptor() ([]byte, []int) {
	return file_todolist_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteToDoRes) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ListToDosReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListToDosReq) Reset() {
	*x = ListToDosReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todolist_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListToDosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToDosReq) ProtoMessage() {}

func (x *ListToDosReq) ProtoReflect() protoreflect.Message {
	mi := &file_todolist_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToDosReq.ProtoReflect.Descriptor instead.
func (*ListToDosReq) Descriptor() ([]byte, []int) {
	return file_todolist_proto_rawDescGZIP(), []int{9}
}

type ListToDosRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Todos []*ToDo `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
}

func (x *ListToDosRes) Reset() {
	*x = ListToDosRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todolist_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListToDosRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToDosRes) ProtoMessage() {}

func (x *ListToDosRes) ProtoReflect() protoreflect.Message {
	mi := &file_todolist_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToDosRes.ProtoReflect.Descriptor instead.
func (*ListToDosRes) Descriptor() ([]byte, []int) {
	return file_todolist_proto_rawDescGZIP(), []int{10}
}

func (x *ListToDosRes) GetTodos() []*ToDo {
	if x != nil {
		return x.Todos
	}
	return nil
}

var File_todolist_proto protoreflect.FileDescriptor

var file_todolist_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x64, 0x0a, 0x04, 0x54, 0x6f,
	0x44, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x33, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x44, 0x6f, 0x52, 0x65,
	0x71, 0x12, 0x22, 0x0a, 0x04, 0x74, 0x6f, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x54, 0x6f, 0x44, 0x6f, 0x52,
	0x04, 0x74, 0x6f, 0x64, 0x6f, 0x22, 0x33, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x6f, 0x44, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x04, 0x74, 0x6f, 0x64, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x2e,
	0x54, 0x6f, 0x44, 0x6f, 0x52, 0x04, 0x74, 0x6f, 0x64, 0x6f, 0x22, 0x33, 0x0a, 0x0d, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x44, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x04, 0x74,
	0x6f, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x6f, 0x64, 0x6f,
	0x6c, 0x69, 0x73, 0x74, 0x2e, 0x54, 0x6f, 0x44, 0x6f, 0x52, 0x04, 0x74, 0x6f, 0x64, 0x6f, 0x22,
	0x33, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x44, 0x6f, 0x52, 0x65, 0x73,
	0x12, 0x22, 0x0a, 0x04, 0x74, 0x6f, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x54, 0x6f, 0x44, 0x6f, 0x52, 0x04,
	0x74, 0x6f, 0x64, 0x6f, 0x22, 0x1d, 0x0a, 0x0b, 0x52, 0x65, 0x61, 0x64, 0x54, 0x6f, 0x44, 0x6f,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x31, 0x0a, 0x0b, 0x52, 0x65, 0x61, 0x64, 0x54, 0x6f, 0x44, 0x6f, 0x52,
	0x65, 0x73, 0x12, 0x22, 0x0a, 0x04, 0x74, 0x6f, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x54, 0x6f, 0x44, 0x6f,
	0x52, 0x04, 0x74, 0x6f, 0x64, 0x6f, 0x22, 0x1f, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x54, 0x6f, 0x44, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x27, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x54, 0x6f, 0x44, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x0e, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x44, 0x6f, 0x73, 0x52, 0x65, 0x71,
	0x22, 0x34, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x44, 0x6f, 0x73, 0x52, 0x65, 0x73,
	0x12, 0x24, 0x0a, 0x05, 0x74, 0x6f, 0x64, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x54, 0x6f, 0x44, 0x6f, 0x52,
	0x05, 0x74, 0x6f, 0x64, 0x6f, 0x73, 0x32, 0x99, 0x02, 0x0a, 0x0b, 0x54, 0x6f, 0x64, 0x6f, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x6f, 0x44, 0x6f, 0x12, 0x0e, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x2e,
	0x54, 0x6f, 0x44, 0x6f, 0x1a, 0x0e, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x2e,
	0x54, 0x6f, 0x44, 0x6f, 0x12, 0x31, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x64, 0x54, 0x6f, 0x44, 0x6f,
	0x12, 0x15, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x61, 0x64,
	0x54, 0x6f, 0x44, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69,
	0x73, 0x74, 0x2e, 0x54, 0x6f, 0x44, 0x6f, 0x12, 0x2c, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x6f, 0x44, 0x6f, 0x12, 0x0e, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74,
	0x2e, 0x54, 0x6f, 0x44, 0x6f, 0x1a, 0x0e, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74,
	0x2e, 0x54, 0x6f, 0x44, 0x6f, 0x12, 0x3e, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54,
	0x6f, 0x44, 0x6f, 0x12, 0x17, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f, 0x44, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x74,
	0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f,
	0x44, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x3b, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x44,
	0x6f, 0x73, 0x12, 0x16, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x54, 0x6f, 0x44, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x74, 0x6f, 0x64,
	0x6f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x44, 0x6f, 0x73, 0x52,
	0x65, 0x73, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x54, 0x65, 0x65, 0x32, 0x39, 0x31, 0x32, 0x2f, 0x54, 0x6f, 0x2d, 0x44, 0x6f, 0x2d, 0x4c,
	0x69, 0x73, 0x74, 0x2d, 0x47, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_todolist_proto_rawDescOnce sync.Once
	file_todolist_proto_rawDescData = file_todolist_proto_rawDesc
)

func file_todolist_proto_rawDescGZIP() []byte {
	file_todolist_proto_rawDescOnce.Do(func() {
		file_todolist_proto_rawDescData = protoimpl.X.CompressGZIP(file_todolist_proto_rawDescData)
	})
	return file_todolist_proto_rawDescData
}

var file_todolist_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_todolist_proto_goTypes = []interface{}{
	(*ToDo)(nil),          // 0: todolist.ToDo
	(*CreateToDoReq)(nil), // 1: todolist.CreateToDoReq
	(*CreateToDoRes)(nil), // 2: todolist.CreateToDoRes
	(*UpdateToDoReq)(nil), // 3: todolist.UpdateToDoReq
	(*UpdateToDoRes)(nil), // 4: todolist.UpdateToDoRes
	(*ReadToDoReq)(nil),   // 5: todolist.ReadToDoReq
	(*ReadToDoRes)(nil),   // 6: todolist.ReadToDoRes
	(*DeleteToDoReq)(nil), // 7: todolist.DeleteToDoReq
	(*DeleteToDoRes)(nil), // 8: todolist.DeleteToDoRes
	(*ListToDosReq)(nil),  // 9: todolist.ListToDosReq
	(*ListToDosRes)(nil),  // 10: todolist.ListToDosRes
}
var file_todolist_proto_depIdxs = []int32{
	0,  // 0: todolist.CreateToDoReq.todo:type_name -> todolist.ToDo
	0,  // 1: todolist.CreateToDoRes.todo:type_name -> todolist.ToDo
	0,  // 2: todolist.UpdateToDoReq.todo:type_name -> todolist.ToDo
	0,  // 3: todolist.UpdateToDoRes.todo:type_name -> todolist.ToDo
	0,  // 4: todolist.ReadToDoRes.todo:type_name -> todolist.ToDo
	0,  // 5: todolist.ListToDosRes.todos:type_name -> todolist.ToDo
	0,  // 6: todolist.TodoService.CreateToDo:input_type -> todolist.ToDo
	5,  // 7: todolist.TodoService.ReadToDo:input_type -> todolist.ReadToDoReq
	0,  // 8: todolist.TodoService.UpdateToDo:input_type -> todolist.ToDo
	7,  // 9: todolist.TodoService.DeleteToDo:input_type -> todolist.DeleteToDoReq
	9,  // 10: todolist.TodoService.ListToDos:input_type -> todolist.ListToDosReq
	0,  // 11: todolist.TodoService.CreateToDo:output_type -> todolist.ToDo
	0,  // 12: todolist.TodoService.ReadToDo:output_type -> todolist.ToDo
	0,  // 13: todolist.TodoService.UpdateToDo:output_type -> todolist.ToDo
	8,  // 14: todolist.TodoService.DeleteToDo:output_type -> todolist.DeleteToDoRes
	10, // 15: todolist.TodoService.ListToDos:output_type -> todolist.ListToDosRes
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_todolist_proto_init() }
func file_todolist_proto_init() {
	if File_todolist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_todolist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToDo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todolist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateToDoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todolist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateToDoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todolist_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateToDoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todolist_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateToDoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todolist_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadToDoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todolist_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadToDoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todolist_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteToDoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todolist_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteToDoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todolist_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListToDosReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todolist_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListToDosRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_todolist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_todolist_proto_goTypes,
		DependencyIndexes: file_todolist_proto_depIdxs,
		MessageInfos:      file_todolist_proto_msgTypes,
	}.Build()
	File_todolist_proto = out.File
	file_todolist_proto_rawDesc = nil
	file_todolist_proto_goTypes = nil
	file_todolist_proto_depIdxs = nil
}
